title: David Bindel
email: bindel@cornell.edu
description: Numerical Methods for Data Science
baseurl: "~bindel/class/sjtu-summer2018/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
